메모생성 API
00rigin/Feynman_Method pull request #7
Opened 2023-10-09 07:56 UTC by 00rigin

2023-10-12 02:07 UTC, brady-man-847 requested changes

2023-10-12 02:07 UTC, brady-man-847 commented on FM_BE/hawaiianPizza/build.gradle.kts
> +allOpen {
allOpen 은 뭔가요 ?!

2023-10-12 02:07 UTC, brady-man-847 commented on FM_BE/hawaiianPizza/src/main/kotlin/com/pineapple/hawaiianPizza/memo/Memo.kt
> +    private var parent: Memo? = null
props에 parent 제거 했는데 null로 매핑하나용 ?

2023-10-12 02:07 UTC, brady-man-847 commented on FM_BE/hawaiianPizza/src/main/kotlin/com/pineapple/hawaiianPizza/memo/Memo.kt
> +    constructor (title: String, description: String, parent: Memo?) : this(title, description) {
생성자에서 생성 시 parent를 내부적으로 세팅하고 그래서 parent에만 private를 주었군요

2023-10-12 02:07 UTC, brady-man-847 commented on FM_BE/hawaiianPizza/src/main/resources/application.yml
> +    path: /peynman
f...eynman

2023-10-13 06:58 UTC, 00rigin commented on FM_BE/hawaiianPizza/build.gradle.kts
> +allOpen {
어노테이션을 적용할 수 있게 하는 부분입니당!

2023-10-13 06:59 UTC, 00rigin commented on FM_BE/hawaiianPizza/src/main/kotlin/com/pineapple/hawaiianPizza/memo/Memo.kt
> +    constructor (title: String, description: String, parent: Memo?) : this(title, description) {
고롷습니당.. 그것도 있고 부모가 없는 경욷 ㅗ있읍니당

2023-11-05 09:06 UTC, merged